# Generated by Django 3.1.5 on 2021-02-20 07:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandname', models.CharField(max_length=255, verbose_name='ブランド名')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopname', models.CharField(max_length=200, verbose_name='店名')),
                ('treatused', models.CharField(choices=[('有', '有'), ('無', '無')], max_length=200, verbose_name='古着の取扱')),
                ('genre', models.CharField(choices=[('メンズ', 'メンズ'), ('ウィメンズ', 'ウィメンズ'), ('メンズ・ウィメンズ', 'メンズ・ウィメンズ')], max_length=200, verbose_name='ジャンル')),
                ('address', models.CharField(max_length=200, verbose_name='所在地')),
                ('hpurl', models.TextField(blank=True, validators=[django.core.validators.URLValidator()], verbose_name='ホームページURL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('treatbrands', models.ManyToManyField(related_name='取扱ブランド', to='shop_list_pre1.Brand')),
            ],
        ),
    ]
